# syntax=docker/dockerfile:1

# Build and runtime in one image: this service is a single FastAPI process with no compiled
# assets, so a multi-stage build would trade real complexity for an image saving that the
# slim base already gives us.
FROM python:3.12-slim AS runtime

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /usr/local/bin/uv

WORKDIR /app

# Dependencies first, in their own layer: application code changes far more often than the
# lockfile, and this is what keeps a code-only rebuild down to seconds.
COPY pyproject.toml uv.lock ./
# The shared contracts package is a path dependency, and an editable install needs its
# sources present at sync time — so the whole (tiny) tree comes in with the metadata. It is
# generated by `make vendor`; a build from a checkout that never ran it fails here with a
# clear missing-path error rather than a confusing dependency-resolution one.
COPY vendor/agent-contracts vendor/agent-contracts
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-dev

ENV PATH="/app/.venv/bin:$PATH"

# Never root: a compromised process should not own the filesystem it runs on.
RUN useradd --create-home --uid 10001 app && chown -R app:app /app
USER app

EXPOSE 8092

# The orchestrator decides liveness; the image states how to ask.
HEALTHCHECK --interval=10s --timeout=3s --start-period=20s --retries=5 \
    CMD python -c "import urllib.request,os,sys; \
port=os.environ.get('SCHEDULES__SERVICE__PORT','8092'); \
sys.exit(0 if urllib.request.urlopen(f'http://127.0.0.1:{port}/health/live', timeout=2).status==200 else 1)"

CMD ["python", "-m", "agent_schedules"]
