CONTRACTS ?= ../agent-contracts
VENDOR    := vendor/agent-contracts

.DEFAULT_GOAL := help
.PHONY: help vendor install lint test image up down

help: ## Show this help
	@grep -hE '^[a-z-]+:.*?## ' $(MAKEFILE_LIST) | awk -F':.*?## ' '{printf "  %-10s %s\n", $$1, $$2}'

vendor: ## Refresh the vendored copy of agent-contracts (generated; never edit in place)
	@test -d "$(CONTRACTS)" || { \
	  echo "agent-contracts not found at $(CONTRACTS); set CONTRACTS=/path/to/agent-contracts" >&2; \
	  exit 1; }
	@# Removed first rather than rsync --delete: with several sources --delete does not
	@# prune inside the transferred tree, so a renamed package would leave its old
	@# directory behind and the image would ship both.
	@rm -rf $(VENDOR)
	@mkdir -p $(VENDOR)
	@rsync -a --exclude .venv --exclude __pycache__ --exclude .git \
	  "$(CONTRACTS)/src" "$(CONTRACTS)/pyproject.toml" "$(CONTRACTS)/README.md" $(VENDOR)/
	@printf '%s\n' \
	  "Generated by \`make vendor\` from $(CONTRACTS). Edits here are overwritten." \
	  > $(VENDOR)/VENDORED.md

install: ## Sync the dev environment
	uv sync --all-extras

lint: ## Ruff check and format check
	uv run ruff check src tests
	uv run ruff format --check src tests

test: ## Run the test suite
	uv run pytest -q

image: vendor ## Build the container image
	docker build -t $(notdir $(CURDIR)):dev .

up: vendor ## Start the service and its database
	docker compose up -d --build

down: ## Stop everything and drop the volumes
	docker compose down -v
