"""The vendored agent-contracts must match its source.

``vendor/agent-contracts`` is generated by ``make vendor`` and git-ignored, and pyproject
resolves the dependency there — a path outside the repository is outside the Docker build
context, so the image cannot use ``../agent-contracts`` directly.

The cost of that is silent drift: a change made in the real agent-contracts repository does not
reach this service until someone regenerates the copy, and nothing says so. Every Makefile
target that runs tests depends on ``vendor``; running ``pytest`` directly does not, and that
is what most people do.

This is not hypothetical. The same arrangement in agent-memory-service shipped a stale
bifrost-sdk: a fix landed upstream, the vendored copy kept the old code, and the entire
suite passed against it — including the tests written to cover the very behaviour that had
been fixed. A stale vendor fails green, which is why this is a test.

Skipped when the source is not on disk: a CI job that checks out only this repository has
nothing to compare against, and the image build regenerates the copy anyway.
"""

from __future__ import annotations

import filecmp
import os
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
VENDORED = REPO / "vendor" / "agent-contracts" / "src" / "universal_agent_contracts"
SOURCE = (
    Path(os.environ.get("CONTRACTS", REPO.parent / "agent-contracts"))
    / "src"
    / "universal_agent_contracts"
)


def _modules(root: Path) -> dict[str, Path]:
    return {
        str(path.relative_to(root)): path
        for path in sorted(root.rglob("*.py"))
        if "__pycache__" not in path.parts
    }


@pytest.mark.skipif(not SOURCE.is_dir(), reason=f"agent-contracts source not at {SOURCE}")
def test_the_vendored_copy_matches_its_source() -> None:
    assert VENDORED.is_dir(), f"{VENDORED} is missing — run `make vendor`"

    source, vendored = _modules(SOURCE), _modules(VENDORED)
    assert set(vendored) == set(source), (
        "the vendored copy has a different set of modules than the source "
        f"(only in vendor: {sorted(set(vendored) - set(source))}; "
        f"only in source: {sorted(set(source) - set(vendored))}) — run `make vendor`"
    )

    stale = [
        name
        for name, path in source.items()
        if not filecmp.cmp(path, vendored[name], shallow=False)
    ]
    assert not stale, (
        f"the vendored agent-contracts is stale: {sorted(stale)} differ from {SOURCE}. "
        f"Run `make vendor`. Until you do, the suite tests code that is not what ships."
    )
